version: "3"
services:
  projectninung:
    container_name: projectninung
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3333:3333"
      - "3000:3000"
    environment:
      TZ: Asia/Manila
    volumes:
      - ../.devcontainer:/app/.devcontainer
      - ../frontend:/app/frontend
      - ../backend:/app/backend
      - /app/frontend/node_modules
      - /app/backend/node_modules
    depends_on:
      - postgresql
  postgresql:
    container_name: postgresqlcsd
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: csdpassword
      POSTGRES_USER: csdadmin
      POSTGRES_DB: csd
      TZ: Asia/Manila
      PGTZ: Asia/Manila
    volumes:
      - ../.devcontainer/pgdata:/var/lib/postgresql/data
